## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    
    obj = bld.create_ns3_program('cubic-test',
                                ['point-to-point', 'applications', 'internet', 'flow-monitor'])
    obj.source = 'cubic-test.cc'

    obj = bld.create_ns3_program('new-reno-test',
                                ['point-to-point', 'applications', 'internet', 'flow-monitor'])
    obj.source = 'new-reno-test.cc'

